### PR TITLE
Refactor JsonDiff and allow custom equality/equivalence

### PR DESCRIPTION
**Pull request by LouizFC**
This is an initial pull request of https://github.com/flipkart-incubator/zjsonpatch/issues/63.

[ Edited , see the checklist bellow ]

Other thing that I want to do, maybe in this PR too, is organizing the tests in a more "debugable" way. Again I had some difficulties testing the library when making changes to the core. If possible I want to:

1. Switch to either JUnit 5 or kotlin-test. JUnit 5 allows custom messages on every assert fail and more flexibility on parametrized tests. Kotlin-test is a more extreme approach, but it also has a the advantage of having more readable code and many utilities that Java don't have.
2. Standardize all (relevant) test data to be file centric (in json files), also add descriptions to these tests.
3. Rewrite some older tests and organize them by operation.

I think this way will be much easier to create new tests and improve the existing ones.

### CODE REVIEW

**Comment by vishwakarma** [comment]
Thanks, @LouizFC for working on this PR. I will review the code changes as soon as possible.
Further, let's make sure that these changes are backward compatible and don't break when an existing user migrate to new version post this PR changes.

**Comment by LouizFC** [comment]
@vishwakarma The current tests are passing, but as I said, I need to organize the current tests to make sure that the new code doesn't break anything.

**Comment by LouizFC** [comment]
@vishwakarma hey, I began the test refactoring, so I wantes to ask 2 things:

- Is it ok for us to migrate to junit 5?

- With the refactors on the existing classes, should I worry about output compatibility? I am not aiming to make any breaking change, what I want to know the following:

We have issue #18, in the given issue both generated patch and proposed patch are correct, but they are semantically different. Should we prioritize to backward compatibility of our outputs or just "correctness" is enough?

**Comment by vishwakarma** [comment]
Hi @LouizFC 
1. Yes, please migrate to junit5
2. Yes, backward compatibility should be the priority along with correctness, since it would provide a seamless upgrade to clients.
Please let me know if you need any help in achieving any of this.

**Comment by LouizFC** [comment]
Here is a checklist of what I plan to do

## Testing
- [ ] Move older tests to another package
- [ ] Document current behavior and write regression tests
- [ ] Refactor tests to be more file-centric

## Features
- [ ] Refactor JsonDiff internals to make it instantiable and configurable
- [ ] Make instances thread safe by making instances immutable
- [ ] Use pre-configured instances for the current (0.4.4) API
- [ ] Add Numeric equivalence.

**Comment by LouizFC** [comment]
@vishwakarma Hello again. I need to document the current behavior of our outputs (JsonDiff).

I was thinking about generating a bunch of random tests, and then check is these tests cover many cases.

I am aiming to document the current order and priority of each type of generated tests, so when I begin refactoring, the outputs remain the same.

**Comment by LouizFC** [comment]
I got some time to work on this pull request, but I decided to do the changes gradually instead of a big pull request.

I created a project on the Projects tab where I will list what needs to be done

**Pull request closed without merging**
