### PR TITLE
Added RFC6901 Test and Fixes

### PR DESCRIPTION
**Pull request by LouizFC**
This is fixes issue #89.

### CODE REVIEW

**Comment by vishwakarma** [comment]
Hi @LouizFC 
Will this be backward compatible?
Example: If some tries to apply a patch(generated before this change) on Source JSON with this change, will it pass? or do you see any issue? I can make a test to simulate this.

**Comment by LouizFC** [comment]
Hello @vishwakarma 

Only some corner cases will break. All our tests are passing, including all the dinamically generated ones.

The patches, as far as I have tested, are being generated correctly, the problem only appears when applying those patches.

The only patches that will produce different results are the ones that includes in their property names:

- Escaped quotes (  \" )
- Both `~0` and `~1` at same time. 

For example, if you create a diff patch between `{ }` and
```json
{
  "test \"this\"": "value1",
  "and ~0~1": "value2"
}
```
It will produce the following patch:
```json
[
   { "op":"add", "path":"/test \"this\"", "value":"value1" },
   { "op":"add", "path":"/and ~00~01", "value":"value2" }
]
```
Which by all means is correct, and this behavior doesn't change with my PR.

Now, applying those patches against  `{ }`:
#### Current version
```json
// this is incorrect, quotes are being replaced by slashes and the path decoding is messed up
{  
   "test \\this\\":"value1",
   "and ~0/ this ~0/":"value2"
}
```
#### After PR
```json
// this is correct, the final result is identical to our original json
{
  "test \"this\"": "value1",
  "and ~0~1 this ~0~1": "value2"
}
```
### Summary
- Patches generated from previous versions will continue the same.
- Patches generated from json which includes `\"` or both `~1` and `~0` at same time on their property names will be applied differently, breaking backward compatibility.

In my opinion, there will be very feel people affected by this, only some corner cases will break, it is very unusual to see a json with the properties mentioned above. The only cases I can think of are:

- User input is used as property names.
- the property names are generated programmatically, e.g. hashes, identifiers, random strings, etc

While it is good to have our library producing "correct" results, it always a bad to change the behavior of something that people are using in production, that is why this is a complicated decision, That is why this is a decision that I can't take alone.

**Comment by holograph** [comment]
For my money, the best way forward is to provide the old (broken) behaviour via a compatibility flag, and make the correct behaviour the default. I'm all for this change otherwise.

**Comment by LouizFC** [comment]
@holograph  seems fair. I will work on it

**Comment by holograph** [comment]
Well, trying to get better error messages (#94) turned into a whole escapade of dealing with paths more consistently, which lead me to build on this patch and refactor the whole thing to use a proper JSON Pointer (RFC 6901) implementation. It's almost there, you can track progress on the [json-pointer branch](https://github.com/holograph/zjsonpatch/tree/json-pointer) in my fork.

@LouizFC @vishwakarma

**Pull request merged**
