### PR TITLE
Add original value information for the REPLACE information.

### PR DESCRIPTION
**Pull request by MihaiMihalache**
Hi guys!
I added the feature to have available the original value for the REPLACE operation. This is needed on our side but i think it adds value to this library.

Thx!

### CODE REVIEW

**Comment by vishwakarma** [comment]
Thanks @MihaiMihalache for PR.
Shall we keep this as an optional feature, since making it default behavior will increase patch size which may affect users performance.
I would say lets pass it as an optional params while computing diffs, example:  **public static JsonNode asJson(final JsonNode source, final JsonNode target, EnumSet<DiffFlags> flags)**, we could evolve DiffFlags class and use it to handle our new use-case,
Please suggest?

**Comment by MihaiMihalache** [comment]
Hi vishwakarma,
Thank you for your quick review.
I agree with you, we should have it as optional. I will take care of it ASAP.

**Comment by vishwakarma** [comment]
Thanks @MihaiMihalache , i will merge the code release by Wednesday, since my current working laptop has gone for repair. Please let me know if you want the changes in maven repo before that.

**Comment by MihaiMihalache** [comment]
Hey vishwakarma,
Thx for reviewing it. For me Wednesday is ok.

**Pull request merged**
