### PR TITLE
Add compatibility flag for ignoring missing target node in replace operation

### PR DESCRIPTION
**Pull request by mbolgariw**

### CODE REVIEW

**Comment by holograph** [comment]
LGTM, though maybe it’s worth documenting what happens when something is indeed missing

**Comment by mbolgariw** [comment]
"replace" operation is equal to removing the previous value and then adding the new value. 
in the previous versions of this lib it was possible to "replace" a value which didn't exist in the target json, now - the lib enforces that the node to replace must exist in the target json. for sake of backward compatibility this PR ignores the node existence check and just adds the new value.

**Comment by mbolgariw** [comment]
hi @holograph , this pr is needed in the project originated by you :), in order to finally move from the 0.2.x version

**Comment by holograph** [comment]
Huh! Y’all still on 0.2.x?! Jesus. By all means, go for it...

**Comment by mbolgariw** [comment]
i don't seem to have an option to either add reviewers or merge the PR.
please merge the PR, if it looks ok.

**Pull request merged**
