### PR TITLE
Further hardening of error handling (this time for Replace operations)

### PR DESCRIPTION
**Pull request by holograph**

### CODE REVIEW

**Comment by holograph** [comment]
Wait up, found a few more :-)

**Comment by holograph** [comment]
Added a new exception (`InvalidJsonPatchException`, a subclass of `JsonPatchApplicationException`) which gets thrown when the actual patch payload is corrupt + a suitable test.

**Comment by holograph** [comment]
It's ready to go now... assuming I didn't miss anything else.

**Comment by vishwakarma** [comment]
Thanks for PR

**Comment by holograph** [comment]
My pleasure. Thanks for the library, it saved us a bunch of time!

**Pull request merged**
